export { default as Login } from './Login/Login';
export { default as Home } from './Home/Home';
export { default as Cinema } from './Cinema/Cinema';
export { default as Movie } from './Movie/Movie';
export { default as TV } from './Movie/TV';
export { default as Music } from './Music/Music';
export { default as Community } from './Community/Community';
export { default as UserProfile } from './UserProfile/UserProfile';
export { default as NotFound } from './NotFound/NotFound';
